SUBDIRS =
TEMPLATES = pokemons.pjs
CONCATENATED = event.js pokemons.pjs material.js auxiliary.min.js async.js transctl.js sort.js menu.js popup.js
CONCATENATEDTO = pokemons.cjs
INSTALLED = pokemons.cjs waves.js
include $(MASTERDIR)/pokemons.locale.mk
