SUBDIRS =
TEMPLATES = pokemons.pjs
CONCATENATED = event.min.js sort.min.js auxiliary.min.js pokemons.pjs material.js async.js transctl.js menu.js popup.js 
CONCATENATEDTO = pokemons.cjs
INSTALLED = pokemons.cjs waves.js
include $(MASTERDIR)/pokemons.locale.mk
